### ISSUE TITLE
Full history and data permissions

### ISSUE THREAD

**Issue by neko-moe-observer** [necauqua/chronotube#1]
Was going to update this add-on and noticed that it requires new permissions, specifically:

> Access browsing history
> Access your data for all websites

I assume this has something to do with the new feature where the duplicate items in your history are removed so it's not spammed.

If it's possible to scale back these permissions that'd be good, but otherwise I think it would be good to have an explanation on the add-on page and in this repo for *why* these permissions are necessary.

Thanks for the neat add-on!

**Comment by necauqua** [comment]
Browsing history you guessed right, but the 'access data for _all_ websites' is just so supported sites can be added silently (without the popup being up each update asking for perms for new sites).

Right now its only twitch and youtube, but I made it so it is super easy to add support for any other video site which has URL timecodes.
And also additionally I wanted to do it in a way that you only need to change `src/platforms.js` to add support (and don't have to add new url permissions to manifest).

Don't know, for me this reasoning seems ok, but I will add explanations as you suggest, yes

**Comment by neko-moe-observer** [comment]
Hmm, while that's probably more convenient for you as a developer, it's a big risk for an add-on user... Seeing history is defensible since it's necessary for removing those old history entries (although even then it might make sense for that to be an optional feature), but accessing the data on *all* websites is a massive security risk in my view...

I don't mind, for example, that the add-on could know that I've visited my bank's website, but I'm very weary about it being able to read data from my bank's website.

I'd request that you remove the "data from all websites" permission and add sites individually instead. Being able to see what new sites the add-on supports could almost be considered a feature to be honest, so I don't see what's wrong with that. I don't imagine you're gonna add new sites every day, at least not for ever.

**Comment by necauqua** [comment]
Yeah okay, didn't seem too bad to me until I saw it released and you told me too.
I will change it back then, indeed

**Comment by necauqua** [comment]
Don't actually know how you can make permission and and a dependent feature optional for Firefox addon.
Also yeah, Firefox permissions are too broad imo, I would be happy to make the history permission look like 'allow this extension to remove youtube.com history entries' or even 'allow this extension to remove (or just see/modify) the history entries IT created'.

**Comment by neko-moe-observer** [comment]
Yeah I understand that. Permissions are generally too broad in browsers or apps. But as long as you use the minimal amount required and can defend it in the description of the add-on I think it's fine.

Thanks!
