### ISSUE TITLE
Does not work when the video tag was added dymanically

### ISSUE THREAD

**Issue by necauqua** [necauqua/chronotube#2]
Both youtube and twitch make use of some kind of SAP-like page mutations - for example when you go from subscriptions to a video on youtube then the addon simply does not work because this same page (the subscriptions page) got its DOM mutated and URL pushState'd.

Can be fixed with like a mutation observer I guess, just idk if observing the whole document from the addon will induce much lag, will have to test that

**Comment by BadAtIrcBots** [comment]
Maybe you could listen to the onpopstate event to determine whether a video has been clicked on. https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate

**Comment by necauqua** [comment]
Thanks for the suggestion, but these history events (there is also `browser.webNavigation` addon API that allow you to listen to such events too) run too early for video tag to be there (so youtube first changes the url and then mutates the dom) so the mutation observer is still needed and since it's needed anyway I just did it.
You can just do 'search for video tag 5 seconds after history event' but this is meh, also the 5 seconds must be a config and idk

Firefox does not reapply content scripts on history change (or at least does not give an option to opt-in such behavior) so I need to make these workarounds.

Looks like it does not affect performace at all so far, tried to avoid any stupid accidental lag causes, will release the finally fixed version soon.

**Comment by BadAtIrcBots** [comment]
I'm no Javascripter but perhaps triggering the main method with media loadstart might work? https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loadstart_event

I set a breakpoint on it, triggered it by clicking on a related video and attached the timeupdate event same way it's done in foreground.js. Seemed to work as expected.

**Comment by necauqua** [comment]
Well, MutationObserver is called not as frequently as you'd expect, and I think that the loadstart event would be called with similar frequency (afaiu it is called for each resource and there is a lot of pictures).

Anyway I ensured that each video tag is processed only once and you can literally change two lines from MutationObserver to some event or anything, if this would be ever needed, thanks.

Also wait, looked closer at the doc you linked, shoudn't you listen to loadstart event _on the element itself_? Like on the video to watch when the corresponding resource starts loading. Or can you attach it to say a document element and then receive events for all resources (images and so on, as I've said)? In the first case it does not solve the issue of _finding_ the video tag itself after it was added dynamically, and about second case I was talking above.

Anyway, the last version finally works flawlessly, at least for me.

**Comment by BadAtIrcBots** [comment]
I think media loadstart is only for <video> and <audio>? Eitherway though I think you're correct, I was lazy and using breakpoints so didn't realize.
